//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Prime", ReplyAction="http://tempuri.org/IService1/PrimeResponse")]
        string Prime(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Prime", ReplyAction="http://tempuri.org/IService1/PrimeResponse")]
        System.Threading.Tasks.Task<string> PrimeAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigit", ReplyAction="http://tempuri.org/IService1/SumDigitResponse")]
        int SumDigit(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumDigit", ReplyAction="http://tempuri.org/IService1/SumDigitResponse")]
        System.Threading.Tasks.Task<int> SumDigitAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        string ReverseString(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHtml", ReplyAction="http://tempuri.org/IService1/PrintHtmlResponse")]
        string PrintHtml(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHtml", ReplyAction="http://tempuri.org/IService1/PrintHtmlResponse")]
        System.Threading.Tasks.Task<string> PrintHtmlAsync(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort5", ReplyAction="http://tempuri.org/IService1/Sort5Response")]
        int[] Sort5(int[] ints, int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort5", ReplyAction="http://tempuri.org/IService1/Sort5Response")]
        System.Threading.Tasks.Task<int[]> Sort5Async(int[] ints, int order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Prime(int num) {
            return base.Channel.Prime(num);
        }
        
        public System.Threading.Tasks.Task<string> PrimeAsync(int num) {
            return base.Channel.PrimeAsync(num);
        }
        
        public int SumDigit(int num) {
            return base.Channel.SumDigit(num);
        }
        
        public System.Threading.Tasks.Task<int> SumDigitAsync(int num) {
            return base.Channel.SumDigitAsync(num);
        }
        
        public string ReverseString(string str) {
            return base.Channel.ReverseString(str);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string str) {
            return base.Channel.ReverseStringAsync(str);
        }
        
        public string PrintHtml(string tag, string data) {
            return base.Channel.PrintHtml(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintHtmlAsync(string tag, string data) {
            return base.Channel.PrintHtmlAsync(tag, data);
        }
        
        public int[] Sort5(int[] ints, int order) {
            return base.Channel.Sort5(ints, order);
        }
        
        public System.Threading.Tasks.Task<int[]> Sort5Async(int[] ints, int order) {
            return base.Channel.Sort5Async(ints, order);
        }
    }
}
